loadbalancerName: alb2-name
address: 127.0.0.1
domains: []
nodeSelector: {}
loadbalancerType: nginx
replicas: 3
enableGC: "false"
enablePrometheus: "true"
enablePortprobe: "true"
enableIPV6: "true"
enableHTTP2: "true"
enableIngress: "true"
enablePortProject: false
defaultSSLCert: ""
defaultSSLStrategy: Never
ingressHTTPPort: 80
ingressHTTPSPort: 443
metricsPort: 1936
enableProfile: false
workerLimit: 8
resyncPeriod: 1800
backlog: 1024
global:
  platformscenario: base
  labelBaseDomain: alauda.io
  namespace: alauda-system
  registry:
    address: harbor.alauda.cn
  images:
    alb2:
      code: gitlab-ce.alauda.cn/container-platform/alb2
      support_arm: true
      repository: acp/alb2
      tag: v3.0.4
resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 128Mi
project: ""
projects: []
displayName: ""
