/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v3 "alb2/pkg/apis/alauda/v3"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAlaudaLoadBalancers implements AlaudaLoadBalancerInterface
type FakeAlaudaLoadBalancers struct {
	Fake *FakeCrdV3
}

var alaudaloadbalancersResource = schema.GroupVersionResource{Group: "alauda.io", Version: "v3", Resource: "alaudaloadbalancers"}

var alaudaloadbalancersKind = schema.GroupVersionKind{Group: "alauda.io", Version: "v3", Kind: "AlaudaLoadBalancer"}

// Get takes name of the alaudaLoadBalancer, and returns the corresponding alaudaLoadBalancer object, and an error if there is any.
func (c *FakeAlaudaLoadBalancers) Get(name string, options v1.GetOptions) (result *v3.AlaudaLoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(alaudaloadbalancersResource, name), &v3.AlaudaLoadBalancer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AlaudaLoadBalancer), err
}

// List takes label and field selectors, and returns the list of AlaudaLoadBalancers that match those selectors.
func (c *FakeAlaudaLoadBalancers) List(opts v1.ListOptions) (result *v3.AlaudaLoadBalancerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(alaudaloadbalancersResource, alaudaloadbalancersKind, opts), &v3.AlaudaLoadBalancerList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v3.AlaudaLoadBalancerList{ListMeta: obj.(*v3.AlaudaLoadBalancerList).ListMeta}
	for _, item := range obj.(*v3.AlaudaLoadBalancerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested alaudaLoadBalancers.
func (c *FakeAlaudaLoadBalancers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(alaudaloadbalancersResource, opts))
}

// Create takes the representation of a alaudaLoadBalancer and creates it.  Returns the server's representation of the alaudaLoadBalancer, and an error, if there is any.
func (c *FakeAlaudaLoadBalancers) Create(alaudaLoadBalancer *v3.AlaudaLoadBalancer) (result *v3.AlaudaLoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(alaudaloadbalancersResource, alaudaLoadBalancer), &v3.AlaudaLoadBalancer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AlaudaLoadBalancer), err
}

// Update takes the representation of a alaudaLoadBalancer and updates it. Returns the server's representation of the alaudaLoadBalancer, and an error, if there is any.
func (c *FakeAlaudaLoadBalancers) Update(alaudaLoadBalancer *v3.AlaudaLoadBalancer) (result *v3.AlaudaLoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(alaudaloadbalancersResource, alaudaLoadBalancer), &v3.AlaudaLoadBalancer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AlaudaLoadBalancer), err
}

// Delete takes name of the alaudaLoadBalancer and deletes it. Returns an error if one occurs.
func (c *FakeAlaudaLoadBalancers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(alaudaloadbalancersResource, name), &v3.AlaudaLoadBalancer{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAlaudaLoadBalancers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(alaudaloadbalancersResource, listOptions)

	_, err := c.Fake.Invokes(action, &v3.AlaudaLoadBalancerList{})
	return err
}

// Patch applies the patch and returns the patched alaudaLoadBalancer.
func (c *FakeAlaudaLoadBalancers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v3.AlaudaLoadBalancer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(alaudaloadbalancersResource, name, data, subresources...), &v3.AlaudaLoadBalancer{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v3.AlaudaLoadBalancer), err
}
