/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "alauda.io/alb2/pkg/apis/alauda/v1"
	scheme "alauda.io/alb2/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FrontendsGetter has a method to return a FrontendInterface.
// A group's client should implement this interface.
type FrontendsGetter interface {
	Frontends(namespace string) FrontendInterface
}

// FrontendInterface has methods to work with Frontend resources.
type FrontendInterface interface {
	Create(ctx context.Context, frontend *v1.Frontend, opts metav1.CreateOptions) (*v1.Frontend, error)
	Update(ctx context.Context, frontend *v1.Frontend, opts metav1.UpdateOptions) (*v1.Frontend, error)
	UpdateStatus(ctx context.Context, frontend *v1.Frontend, opts metav1.UpdateOptions) (*v1.Frontend, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Frontend, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FrontendList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Frontend, err error)
	FrontendExpansion
}

// frontends implements FrontendInterface
type frontends struct {
	client rest.Interface
	ns     string
}

// newFrontends returns a Frontends
func newFrontends(c *CrdV1Client, namespace string) *frontends {
	return &frontends{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the frontend, and returns the corresponding frontend object, and an error if there is any.
func (c *frontends) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Frontend, err error) {
	result = &v1.Frontend{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("frontends").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Frontends that match those selectors.
func (c *frontends) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FrontendList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FrontendList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("frontends").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested frontends.
func (c *frontends) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("frontends").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a frontend and creates it.  Returns the server's representation of the frontend, and an error, if there is any.
func (c *frontends) Create(ctx context.Context, frontend *v1.Frontend, opts metav1.CreateOptions) (result *v1.Frontend, err error) {
	result = &v1.Frontend{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("frontends").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(frontend).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a frontend and updates it. Returns the server's representation of the frontend, and an error, if there is any.
func (c *frontends) Update(ctx context.Context, frontend *v1.Frontend, opts metav1.UpdateOptions) (result *v1.Frontend, err error) {
	result = &v1.Frontend{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("frontends").
		Name(frontend.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(frontend).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *frontends) UpdateStatus(ctx context.Context, frontend *v1.Frontend, opts metav1.UpdateOptions) (result *v1.Frontend, err error) {
	result = &v1.Frontend{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("frontends").
		Name(frontend.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(frontend).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the frontend and deletes it. Returns an error if one occurs.
func (c *frontends) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("frontends").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *frontends) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("frontends").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched frontend.
func (c *frontends) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Frontend, err error) {
	result = &v1.Frontend{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("frontends").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
