apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.23.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: alb-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Alb Operator description
  displayName: Alb Operator
  icon:
  - base64data: ""
    mediatype: ""
  install: null
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - alb-operator
  links:
  - name: alb Operator
    url: https://alauda.cn
  maintainers:
  - email: congwu@alauda.cn
    name: congwu
  - email: yjai@alauda.io
    name: yjai
  maturity: alpha
  provider:
    name: alauda
    url: alauda.cn
  version: 0.0.0