apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alaudaloadbalancer2.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: alaudaloadbalancer2
    singular: alaudaloadbalancer2
    kind: ALB2
    shortNames:
    - alb2
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: spec contains specification parameters for a alb2 resource
          type: object
          properties:
            address:
              description: address is used to shown access address if no domain
              type: string
            bind_address:
              description: deprecated field
              type: string
            type:
              description: deprecated field
              type: string
            domains:
              description: deprecated field
              anyOf:
              - type: array
                items:
                  type: string
              - type: null
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: frontends.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: frontends
    singular: frontend
    kind: Frontend
    shortNames:
    - ft
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: spec contains specification parameters for a frontend resource
          type: object
          properties:
            port:
              description: port means which port nginx should listen on
              type: integer
            protocol:
              description: protocol means which protocol for this port, enum var
              type: string
              enum:
                - "http"
                - "https"
                - "tcp"
            certificate_name:
              description: certificate_name is the default certificate
              type: string
            serviceGroup:
              description: serviceGroup is a group of k8s services
              type: object
              properties:
                session_affinity_policy:
                  description: session_affinity_policy is the hash algo
                  type: string
                session_affinity_attribute:
                  description: session_affinity_attribute is needed if using cookie hash
                  type: string
                services:
                  description: services is a list of k8s services
                  type: array
                  items:
                    description: items is a list of service
                    type: object
                    properties:
                      name:
                        description: name is the k8s service name
                        type: string
                      namespace:
                        description: namespace is the k8s service namespace
                        type: string
                      port:
                        description: port is the k8s service port
                        type: integer
                      weight:
                        description: weight is the weight of this service
                        type: integer
            source:
              type: object
              description: source indicate who created this resource, ingress or UI
              properties:
                name:
                  description: source name
                  type: string
                namespace:
                  description: source namespace
                  type: string
                type:
                  description: source type
                  type: string
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rules.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - rl
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: spec contains specification parameters for a rule resource
          type: object
          properties:
            description:
              description: the description of this rule
              type: string
            domain:
              description: domain of this rule
              type: string
            dsl:
              description: internal dsl
              type: string
            priority:
              description: weight of this rule
              type: integer
            type:
              description: deprecated field
              type: string
            url:
              description: url rewrite src
              type: string
            certificate_name:
              description: certificate_name is the default certificate
              type: string
            rewrite_target:
              description: url rewrite dest
              type: string
            enableCORS:
              description: if need enable cors headers
              type: boolean
            backendProtocol:
              description: proxy_pass backend protocol, http or https
              type: string
            serviceGroup:
              description: serviceGroup is a group of k8s services
              type: object
              properties:
                session_affinity_policy:
                  description: session_affinity_policy is the hash algo
                  type: string
                session_affinity_attribute:
                  description: session_affinity_attribute is needed if using cookie hash
                  type: string
                services:
                  description: services is a list of k8s services
                  type: array
                  items:
                    description: items is a list of service
                    type: object
                    properties:
                      name:
                        description: name is the k8s service name
                        type: string
                      namespace:
                        description: namespace is the k8s service namespace
                        type: string
                      port:
                        description: port is the k8s service port
                        type: integer
                      weight:
                        description: weight is the weight of this service
                        type: integer
            source:
              type: object
              description: source indicate who created this resource, ingress or UI
              properties:
                name:
                  description: source name
                  type: string
                namespace:
                  description: source namespace
                  type: string
                type:
                  description: source type
                  type: string
---
# Deployed in business cluster
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: features.infrastructure.alauda.io
spec:
  group: infrastructure.alauda.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  version: v1alpha1
  scope: Cluster
  names:
    plural: features
    singular: feature
    kind: Feature
    shortNames:
    - ft
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            # 描述插件的类型。比如是监控还是日志还是应用
            type:
              description: 'type defines the type of the addon. eg: metric, log, application etc...'
              type: string
            # 描述类型的具体实例。比如监控的prometheus，比如日志的fluentd
            instanceType:
              description: 'instanceType defines the tool to support the type. eg: prometheus, fluentd'
            # 描述当前的版本
            version:
              description: 'version defines the version of the addon. it is used to compare with the version of the instance to descide upgrade or not'
              type: string
            # 如果当前addons对外提供服务，那么服务的地址信息。
            accessInfo:
              description: 'accessInfo defines the server info,if the addon support some interface to access. eg promtheus, grafana'
              type: object
            # 当前addons的所有资源信息
            resourceInfo:
              description: 'resourceInfo defines all the resource the addons contains'
              type: array
              items:
                properties:
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
            # 部署时候需要用到的信息。
            deployInfo:
              type: object
          required:
          - version
          - type
        # 当前addons的状态。
        status:
          properties:
            status:
              type: object
