apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-wc-nginx-config
  namespace: alb-wc
data:
  nginx-config: |
    worker_processes  4;

    events {
        worker_connections  1024;
    }

    http {
        server {
            listen 80;
            location / {
              content_by_lua_block {
                      ngx.say("Hello, world!")
              }
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-resty
  namespace: alb-wc
  labels:
    k8s-app: echo-resty
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: echo-resty
  template:
    metadata:
      labels:
        k8s-app: echo-resty
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: echo-resty
        image: yannrobert/docker-nginx
        resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "8G"
              cpu: "8"
        volumeMounts:
          - name: config-volume
            mountPath: /etc/nginx
        command:
         - sh
         - -c
         - 'nginx && tail -f /dev/null' 
        ports:
        - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: alb-wc-nginx-config
            items:
            - key: nginx-config
              path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: echo-resty
  namespace: alb-wc
  labels:
    k8s-app: echo-resty
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: echo-resty
