run: 
  timeout: 4600s 
  skip-dirs: 
    - test
linters:
  enable: 
    - gocritic
    - gofumpt
    - goimports
    - misspell
    - predeclared
    - revive
    - unconvert
    - unused 
issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:" # gateway status deprecated.  gv1.GatewayReasonReady is deprecated: Ready is reserved for future use 
    - path: _test\.go
      linters:
        - errcheck
linters-settings:
  errcheck:
    check-blank: true
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
      - badCond
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: true