[default]
SCHEDULER = "kubernetes"
KUBERNETES_TIMEOUT = 30
INTERVAL = 10
CERTIFICATE_DIRECTORY = "/alb/certificates"
RECORD_POST_BODY = false
USE_ENDPOINT = true
USE_POD_HOST_IP = true
NEW_CONFIG_PATH = "haproxy.cfg.new"
OLD_CONFIG_PATH = "haproxy.cfg"

#timeout for http request
timeout = 30

# for test
KUBERNETES_SERVER = "https://127.0.0.1:6443"
KUBERNETES_BEARERTOKEN = "dbf41d.ae570f0cc2527039"
LB_TYPE="haproxy"
NAME="test1"
NAMESPACE="default"
HAPROXY_TEMPLATE_PATH="template/haproxy/haproxy.tmpl"

[labels]
name = "alb2.alauda.io/name"
frontend = "alb2.alauda.io/frontend"