[default]
LB_TYPE = "nginx"
SCHEDULER = "kubernetes"
KUBERNETES_TIMEOUT = 30
INTERVAL = 10
CERTIFICATE_DIRECTORY = "/alb/certificates"
TWEAK_DIRECTORY = "/alb/tweak/"
RECORD_POST_BODY = false
USE_ENDPOINT = true
USE_POD_HOST_IP = true
RELOAD_TIMEOUT = 600
#timeout for http request
timeout = 30
INCREMENT_SYNC = true
FULL_SYNC = true
RELOAD_NGINX = true
ROTATE_LOG = true
ROTATE_INTERVAL = 20
STATUSFILE_PARENTPATH = "/var/run/alb/last_status"
RESYNC_PERIOD = 300
# for test
KUBERNETES_SERVER = "https://127.0.0.1:6443"
KUBERNETES_BEARERTOKEN = "dbf41d.ae570f0cc2527039"
NAME = "test1"
NAMESPACE = "default"
NGINX_TEMPLATE_PATH = "template/nginx/nginx.tmpl"
NEW_POLICY_PATH = "policy.new"
INGRESS_HTTP_PORT= "80"
INGRESS_HTTPS_PORT= "443"

[labels]
bindkey = "loadbalancer.%s/bind"
name = "alb2.%s/name"
frontend = "alb2.%s/frontend"
lock = "alb2.%s/locker"
source_type = "alb2.%s/source-type"
source_name = "alb2.%s/source-name"
source_ingress_version = "alb2.%s/source-ingress-version"
