[default]
LB_TYPE = "nginx"
SCHEDULER = "kubernetes"
KUBERNETES_TIMEOUT = 30
INTERVAL = 10
CERTIFICATE_DIRECTORY = "/alb/certificates"
RECORD_POST_BODY = false
USE_ENDPOINT = true
USE_POD_HOST_IP = true
NEW_CONFIG_PATH = "haproxy.cfg.new"
OLD_CONFIG_PATH = "haproxy.cfg"

#timeout for http request
timeout = 30

# for test
KUBERNETES_SERVER = "https://127.0.0.1:6443"
KUBERNETES_BEARERTOKEN = "dbf41d.ae570f0cc2527039"
NAME = "test1"
NAMESPACE = "default"
HAPROXY_TEMPLATE_PATH = "template/haproxy/haproxy.tmpl"
NGINX_TEMPLATE_PATH = "template/nginx/nginx.tmpl"
NEW_POLICY_PATH = "policy.new"
OLD_POLICY_PATH = "policy"

[labels]
bindkey = "loadbalancer.alauda.io/bind"
name = "alb2.alauda.io/name"
frontend = "alb2.alauda.io/frontend"
lock = "alb2.alauda.io/locker"
source_type = "alb2.alauda.io/source-type"
source_name = "alb2.alauda.io/source-name"
