required = [
# required for code-generator release-1.9
#  "k8s.io/apimachinery/pkg/apimachinery/registered",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
#  "k8s.io/code-generator/cmd/lister-gen",
#  "k8s.io/code-generator/cmd/informer-gen",
]

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "github.com/fatih/set"
  version = "0.2.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# Prevent dep from pruning build scripts and codegen templates
[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false
