
[[constraint]]
  branch = "master"
  name = "bitbucket.org/mathildetech/qcloud-sdk-go"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.8"

[[constraint]]
  branch = "master"
  name = "github.com/denverdino/aliyungo"

[[constraint]]
  name = "github.com/gambol99/go-marathon"
  version = "0.7.1"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"
  source = "https://github.com/alauda/glog.git"

[[constraint]]
  name = "github.com/parnurzeal/gorequest"
  version = "0.2.15"

[[constraint]]
  name = "gopkg.in/fatih/set.v0"
  version = "0.1.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
