required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
]

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/fatih/set"
  version = "0.2.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "12.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.15"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/thoas/go-funk"
  version = "0.4"

[[constraint]]
  name = "github.com/evanphx/json-patch"
  version = "v4.5.0"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "v1.3.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

# Prevent dep from pruning build scripts and codegen templates
[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false
