[default]
LB_TYPE = "nginx"
SCHEDULER = "kubernetes"
KUBERNETES_TIMEOUT = 30
INTERVAL = 5
TWEAK_DIRECTORY = "/alb/tweak/"
RECORD_POST_BODY = false
USE_POD_HOST_IP = true
RELOAD_TIMEOUT = 600
#timeout for http request
timeout = 30
FULL_SYNC = true
RELOAD_NGINX = true
STATUSFILE_PARENTPATH = "/alb/last_status"
RESYNC_PERIOD = 300
# for test
KUBERNETES_SERVER = "https://127.0.0.1:6443"
KUBERNETES_BEARERTOKEN = "dbf41d.ae570f0cc2527039"
NAME = "test1"
NAMESPACE = "default"
NGINX_TEMPLATE_PATH = "template/nginx/nginx.tmpl"
NEW_POLICY_PATH = "policy.new"
INGRESS_HTTP_PORT= "80"
INGRESS_HTTPS_PORT= "443"
LEADER_LEASE_DURATION = 30
LEADER_RENEW_DEADLINE = 15
LEADER_RETRY_PERIOD = 5
[labels]
bindkey = "loadbalancer.%s/bind"
name = "alb2.%s/name"
frontend = "alb2.%s/frontend"
leader = "alb2.%s/leader"
source_type = "alb2.%s/source-type"
source_name_hash = "alb2.%s/source-name-hash"
source_ingress_version = "alb2.%s/source-ingress-version"
source_ingress_rule_index = "alb2.%s/source-ingress-rule-index"
source_ingress_path_index = "alb2.%s/source-ingress-path-index"
