{{ $fullProjects := append .Values.projects .Values.project | uniq }}
apiVersion: crd.alauda.io/v1
kind: ALB2
metadata:
  name: {{ .Values.loadbalancerName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- range $fullProjects }}
    {{ if . }}
    project.{{ $.Values.global.labelBaseDomain }}/{{ . }}: "true"
    {{ end}}
    {{- end}}
    {{ if .Values.enablePortProject }}
    {{ .Values.global.labelBaseDomain }}/role: "port"
    {{ end}}
  annotations:
    {{ .Values.global.labelBaseDomain }}/display-name: {{ .Values.displayName }}
spec:
  address: {{ .Values.address }}
  bind_address: ''
  domains: {{ .Values.Domains }}
  iaas_id: ''
  type: {{ .Values.loadbalancerType }}
