{{- if .Values.defaultAlb }}
{{- $global := .Values.global }}
{{- $value_without_global := unset .Values "global" }}
{{- $cfg :=  $value_without_global }}
{{ $fullProjects := .Values.projects  | uniq }}
apiVersion: crd.alauda.io/v2beta1
kind: ALB2
metadata:
  name: {{ .Values.loadbalancerName }} 
  namespace: {{ $global.namespace }}
  labels:
    alb.{{ $global.labelBaseDomain}}/managed-by: alb-operator
    alb.{{ $global.labelBaseDomain}}/migrate-from: sentry 
    alb.{{ $global.labelBaseDomain}}/deploy-by: sentry 
    {{- range $fullProjects }}
    {{ if . }}
    project.{{ $global.labelBaseDomain }}/{{ . }}: "true"
    {{ end}}
    {{- end}}
  annotations:
    {{ $global.labelBaseDomain }}/display-name: {{ .Values.displayName |quote }}
    helm.sh/waitResources: "[{\"apiVersion\": \"apps/v1\", \"kind\": \"Deployment\", \"namespace\": \"{{ .Release.Namespace }}\", \"name\": \"{{ .Values.loadbalancerName }}\"}]"
    alb.{{ $global.labelBaseDomain }}/migrate-backup: | 
        {{ $cfg | toJson }}
    update-mode: put
spec:
  address: {{ .Values.address | quote }}
  type: "nginx" 
  config: 
{{ $cfg | toYaml | indent 4 }}
{{- end }}