{{- if eq .Values.operatorDeployMode "deployment" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: "alb-operator"
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if .Values.defaultAlb }}
    helm.sh/waitResources: '[{"apiVersion": "apps/v1", "kind": "Deployment", "namespace": "{{ .Values.global.namespace }}", "name": "alb-operator"},{"apiVersion": "apps/v1", "kind": "Deployment", "namespace": "{{ .Values.global.namespace }}", "name": "{{.Values.loadbalancerName}}"}]'
    {{- else }}
    helm.sh/waitResources: '[{"apiVersion": "apps/v1", "kind": "Deployment", "namespace": "{{ .Values.global.namespace }}", "name": "alb-operator"}]'
    {{- end }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: {{ .Values.operatorReplicas }}
  selector:
    matchLabels:
      name: alb-operator
  template:
    metadata:
      labels:
        name: alb-operator
    spec:
      serviceAccountName: alb-operator
      nodeSelector:
        kubernetes.io/os: linux
        {{- range $key, $value := .Values.global.nodeSelector }}
        {{ $key | quote }}: {{ $value | quote  }}
        {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    name: alb-operator
                topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: ALB_IMAGE
              value: "{{ .Values.global.registry.address }}/{{ .Values.global.images.alb2.repository }}:{{ .Values.global.images.alb2.tag }}"
            - name: NGINX_IMAGE
              value: "{{ .Values.global.registry.address }}/{{ .Values.global.images.nginx.repository }}:{{ .Values.global.images.nginx.tag }}"
            - name: VERSION
              value: "{{ .Chart.Version }}"
            - name: IMAGE_PULL_SECRETS
              value: '{{ .Values.global.registry.imagePullSecrets| join "," }}'
            - name: IMAGE_PULL_POLICY
              value: "{{ .Values.operator.albImagePullPolicy }}"
            - name: LABEL_BASE_DOMAIN
              value: "{{ .Values.global.labelBaseDomain }}"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          command:
            - /alb/ctl/operator
          image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.alb2.repository }}:{{ .Values.global.images.alb2.tag }}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          name: alb-operator
          securityContext:
            runAsGroup: 697
            runAsNonRoot: true
            runAsUser: 697
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false  
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
            limits:
              cpu: 1 
              memory: 1Gi 
              ephemeral-storage: 500Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/cpaas-system
          operator: Exists
{{- end }}