{{- if eq .Values.operatorDeployMode "csv" }}
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: "[]"
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.23.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: alb-operator.v0.1.0
  namespace: "{{ .Values.global.namespace }}"
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: "负载均衡（Load Balancer）是将流量分发到容器实例的服务。通过负载均衡功能，自动分配计算组件的访问流量，转发给计算组件的容器实例。负载均衡可以提高计算组件的容错能力，扩展计算组件的对外服务能力，提高应用的可用性。"
  displayName: Alb Operator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    strategy: deployment
    spec:
      deployments:
        - name: alb-operator
          spec:
            strategy:
              type: RollingUpdate
              rollingUpdate:
                maxUnavailable: 1
                maxSurge: 1
            replicas: 1
            selector:
              matchLabels:
                name: alb-operator
            template:
              metadata:
                labels:
                  name: alb-operator
              spec:
                nodeSelector:
                  kubernetes.io/os: linux
                affinity:
                  podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      - labelSelector:
                          matchLabels:
                            name: alb-operator
                        topologyKey: kubernetes.io/hostname
                containers:
                  - env:
                      - name: ALB_IMAGE
                        value: "{{ .Values.global.registry.address }}/{{ .Values.global.images.alb2.repository }}:{{ .Values.global.images.alb2.tag }}"
                      - name: NGINX_IMAGE
                        value: "{{ .Values.global.registry.address }}/{{ .Values.global.images.nginx.repository }}:{{ .Values.global.images.nginx.tag }}"
                      - name: VERSION
                        value: "{{ .Chart.Version }}"
                      - name: LABEL_BASE_DOMAIN
                        value: "{{ .Values.global.labelBaseDomain }}"
                      - name: MY_POD_NAME
                        valueFrom:
                          fieldRef:
                            apiVersion: v1
                            fieldPath: metadata.name
                    command:
                      - /alb/ctl/operator
                    image: "{{ .Values.global.registry.address }}/{{ .Values.global.images.alb2.repository }}:{{ .Values.global.images.alb2.tag }}"
                    imagePullPolicy: IfNotPresent
                    livenessProbe:
                      failureThreshold: 5
                      tcpSocket:
                        port: 8081
                      initialDelaySeconds: 10
                      periodSeconds: 60
                      successThreshold: 1
                      timeoutSeconds: 5
                    name: alb-operator
                    resources:
                      requests:
                        cpu: 200m
                        ephemeral-storage: 500Mi
                        memory: 256Mi
                tolerations:
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/master
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/control-plane
                    operator: Exists
                  - effect: NoSchedule
                    key: node-role.kubernetes.io/cpaas-system
                    operator: Exists
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - alb-operator
  links:
    - name: alb Operator
      url: https://alauda.cn
  maintainers:
    - email: congwu@alauda.cn
      name: congwu
    - email: yjai@alauda.io
      name: yjai
  maturity: alpha
  provider:
    name: alauda
    url: alauda.cn
  version: 0.1.0

{{- end }}