apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  {{- range $_, $v := .Values.global.registry.imagePullSecrets }}
  - name: {{ $v }}
  {{- end }}
metadata:
  name: alb-operator
  namespace: {{.Values.global.namespace}}
