{
 "title": "ALB Status",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_http_connections, namespace)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(nginx_http_connections{namespace=~\"$namespace\"}, service)"
    }
   },
   { "name": "vmcluster", "label": "Cluster", "query": { "query": "label_values(up, vmcluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "current active connections in alb",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nginx_http_connections{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "stat",
   "description": "last 5 minutes requests",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "description": "The ratio of 4XX and 5XX requests per second on the current ALB over the last 5 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", status=~\"[4-5].*\"}[5m]))/(sum(irate(nginx_http_status{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m])) + 0.01)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "The average latency of requests on the current ALB over the last 5 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_http_request_duration_seconds_sum{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m]))/sum(increase(nginx_http_request_duration_seconds_count{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The CPU usage of the current ALB",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (container_cpu_usage_seconds_total_irate5m{pod_name=~\"$name-.*\", image=\"\", namespace=~\"$namespace\", vmcluster=\"$vmcluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "The memory usage of the current ALB",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_working_set_bytes{pod_name=~\"$name-.*\", image=\"\", namespace=~\"$namespace\", vmcluster=\"$vmcluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive/Transmit",
   "type": "timeseries",
   "description": "The network IO throughput of the current ALB",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod_name) (container_network_receive_bytes_total_irate5m{pod_name=~\"$name-.*\", namespace=~\"$namespace\", vmcluster=\"$vmcluster\"})",
     "legendFormat": "{{pod_name}}/receive"
    },
    {
     "expr": "sum by(pod_name) (container_network_transmit_bytes_total_irate5m{pod_name=~\"$name-.*\", namespace=~\"$namespace\", vmcluster=\"$vmcluster\"})",
     "legendFormat": "{{pod_name}}/transmit"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate",
   "type": "timeseries",
   "description": "Current disk IO throughput of the ALB",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{vmcluster=\"$vmcluster\",namespace=~\"$namespace\",pod=~\"$name-.*\",container!=\"\"}[5m]))",
     "legendFormat": "{{pod}}/write"
    },
    {
     "expr": "sum by(pod) (rate(container_fs_reads_bytes_total{vmcluster=\"$vmcluster\",namespace=~\"$namespace\",pod=~\"$name-.*\",container!=\"\"}[5m]))",
     "legendFormat": "{{pod}}/reads"
    }
   ]
  },
  {
   "title": "Ingress Status",
   "type": "table",
   "description": "The current ingress (qps,request throughput,response throughtput,error ratio, latency of p50,latency of p50 from upstream,latency of p90,latency of p90 from upstream,latency of p99,latency of p99 from upstream ) on the ALB for the last 5 minutes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(source_namespace, source_name) (rate(nginx_http_status{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m]))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "(sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", status=~\"[4-5].*\", source_type=\"ingress\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m])) by (source_namespace, source_name) + 0 )/ (sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", source_type=\"ingress\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m])) by (source_namespace, source_name) + 0.01)",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "sum(rate(nginx_http_request_size_bytes{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (source_namespace,source_name)",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"ingress\"}[5m])) by (source_namespace,source_name)",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    }
   ]
  },
  {
   "title": "HTTPRoute Status",
   "type": "table",
   "description": "The current HTTPRoute (qps,request throughput,response throughtput,error ratio, latency of p50,latency of p50 from upstream,latency of p90,latency of p90 from upstream,latency of p99,latency of p99 from upstream ) on the ALB for the last 5 minutes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(source_namespace, source_name) (rate(nginx_http_status{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m]))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "(sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", status=~\"[4-5].*\", source_type=\"httpRoute\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m])) by (source_namespace, source_name) + 0 )/ (sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", source_type=\"httpRoute\", namespace=~\"$namespace\", pod=~\"$name-.*\"}[5m])) by (source_namespace, source_name) + 0.01)",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (le, source_namespace, source_name))",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "sum(rate(nginx_http_request_size_bytes{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (source_namespace,source_name)",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    },
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"httpRoute\"}[5m])) by (source_namespace,source_name)",
     "legendFormat": "{{source_namespace}}/{{source_name}}"
    }
   ]
  },
  {
   "title": "Rule Status",
   "type": "table",
   "description": "The current non ingress or httproute (qps,request throughput,response throughtput,error ratio, latency of p50,latency of p50 from upstream,latency of p90,latency of p90 from upstream,latency of p99,latency of p99 from upstream ) on the ALB for the last 5 minutes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(namespace, rule) (rate(nginx_http_status{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m]))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (le, namespace, rule))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (le, namespace, rule))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (le, namespace, rule))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "(sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", status=~\"[4-5].*\", source_type=\"\", namespace=~\"$namespace\", pod=~\"$name-.*\", rule!=\"\"}[5m])) by (namespace, rule) + 0 )/ (sum(rate(nginx_http_status{vmcluster=\"$vmcluster\", source_type=\"\", namespace=~\"$namespace\", pod=~\"$name-.*\", rule!=\"\"}[5m])) by (namespace, rule) + 0.01)",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (le, namespace, rule))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (le, namespace, rule))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_http_upstream_request_duration_seconds_bucket{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (le, namespace, rule))",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "sum(rate(nginx_http_request_size_bytes{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (namespace,rule)",
     "legendFormat": "{{namespace}}/{{rule}}"
    },
    {
     "expr": "sum(rate(nginx_http_response_size_bytes{vmcluster=\"$vmcluster\", namespace=~\"$namespace\", pod=~\"$name-.*\", source_type=\"\", rule!=\"\"}[5m])) by (namespace,rule)",
     "legendFormat": "{{namespace}}/{{rule}}"
    }
   ]
  }
 ]
}