/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	alaudav1 "alauda.io/alb2/pkg/apis/alauda/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFrontends implements FrontendInterface
type FakeFrontends struct {
	Fake *FakeCrdV1
	ns   string
}

var frontendsResource = schema.GroupVersionResource{Group: "crd.alauda.io", Version: "v1", Resource: "frontends"}

var frontendsKind = schema.GroupVersionKind{Group: "crd.alauda.io", Version: "v1", Kind: "Frontend"}

// Get takes name of the frontend, and returns the corresponding frontend object, and an error if there is any.
func (c *FakeFrontends) Get(ctx context.Context, name string, options v1.GetOptions) (result *alaudav1.Frontend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(frontendsResource, c.ns, name), &alaudav1.Frontend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.Frontend), err
}

// List takes label and field selectors, and returns the list of Frontends that match those selectors.
func (c *FakeFrontends) List(ctx context.Context, opts v1.ListOptions) (result *alaudav1.FrontendList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(frontendsResource, frontendsKind, c.ns, opts), &alaudav1.FrontendList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &alaudav1.FrontendList{ListMeta: obj.(*alaudav1.FrontendList).ListMeta}
	for _, item := range obj.(*alaudav1.FrontendList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested frontends.
func (c *FakeFrontends) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(frontendsResource, c.ns, opts))

}

// Create takes the representation of a frontend and creates it.  Returns the server's representation of the frontend, and an error, if there is any.
func (c *FakeFrontends) Create(ctx context.Context, frontend *alaudav1.Frontend, opts v1.CreateOptions) (result *alaudav1.Frontend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(frontendsResource, c.ns, frontend), &alaudav1.Frontend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.Frontend), err
}

// Update takes the representation of a frontend and updates it. Returns the server's representation of the frontend, and an error, if there is any.
func (c *FakeFrontends) Update(ctx context.Context, frontend *alaudav1.Frontend, opts v1.UpdateOptions) (result *alaudav1.Frontend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(frontendsResource, c.ns, frontend), &alaudav1.Frontend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.Frontend), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFrontends) UpdateStatus(ctx context.Context, frontend *alaudav1.Frontend, opts v1.UpdateOptions) (*alaudav1.Frontend, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(frontendsResource, "status", c.ns, frontend), &alaudav1.Frontend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.Frontend), err
}

// Delete takes name of the frontend and deletes it. Returns an error if one occurs.
func (c *FakeFrontends) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(frontendsResource, c.ns, name), &alaudav1.Frontend{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFrontends) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(frontendsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &alaudav1.FrontendList{})
	return err
}

// Patch applies the patch and returns the patched frontend.
func (c *FakeFrontends) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *alaudav1.Frontend, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(frontendsResource, c.ns, name, pt, data, subresources...), &alaudav1.Frontend{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.Frontend), err
}
