/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	alaudav1 "alb2/pkg/apis/alauda/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeALB2s implements ALB2Interface
type FakeALB2s struct {
	Fake *FakeCrdV1
	ns   string
}

var alb2sResource = schema.GroupVersionResource{Group: "crd.alauda.io", Version: "v1", Resource: "alb2s"}

var alb2sKind = schema.GroupVersionKind{Group: "crd.alauda.io", Version: "v1", Kind: "ALB2"}

// Get takes name of the aLB2, and returns the corresponding aLB2 object, and an error if there is any.
func (c *FakeALB2s) Get(name string, options v1.GetOptions) (result *alaudav1.ALB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(alb2sResource, c.ns, name), &alaudav1.ALB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.ALB2), err
}

// List takes label and field selectors, and returns the list of ALB2s that match those selectors.
func (c *FakeALB2s) List(opts v1.ListOptions) (result *alaudav1.ALB2List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(alb2sResource, alb2sKind, c.ns, opts), &alaudav1.ALB2List{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &alaudav1.ALB2List{ListMeta: obj.(*alaudav1.ALB2List).ListMeta}
	for _, item := range obj.(*alaudav1.ALB2List).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aLB2s.
func (c *FakeALB2s) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(alb2sResource, c.ns, opts))

}

// Create takes the representation of a aLB2 and creates it.  Returns the server's representation of the aLB2, and an error, if there is any.
func (c *FakeALB2s) Create(aLB2 *alaudav1.ALB2) (result *alaudav1.ALB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(alb2sResource, c.ns, aLB2), &alaudav1.ALB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.ALB2), err
}

// Update takes the representation of a aLB2 and updates it. Returns the server's representation of the aLB2, and an error, if there is any.
func (c *FakeALB2s) Update(aLB2 *alaudav1.ALB2) (result *alaudav1.ALB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(alb2sResource, c.ns, aLB2), &alaudav1.ALB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.ALB2), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeALB2s) UpdateStatus(aLB2 *alaudav1.ALB2) (*alaudav1.ALB2, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(alb2sResource, "status", c.ns, aLB2), &alaudav1.ALB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.ALB2), err
}

// Delete takes name of the aLB2 and deletes it. Returns an error if one occurs.
func (c *FakeALB2s) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(alb2sResource, c.ns, name), &alaudav1.ALB2{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeALB2s) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(alb2sResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &alaudav1.ALB2List{})
	return err
}

// Patch applies the patch and returns the patched aLB2.
func (c *FakeALB2s) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *alaudav1.ALB2, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(alb2sResource, c.ns, name, data, subresources...), &alaudav1.ALB2{})

	if obj == nil {
		return nil, err
	}
	return obj.(*alaudav1.ALB2), err
}
