/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	alaudav1 "alauda.io/alb2/pkg/apis/alauda/v1"
	versioned "alauda.io/alb2/pkg/client/clientset/versioned"
	internalinterfaces "alauda.io/alb2/pkg/client/informers/externalversions/internalinterfaces"
	v1 "alauda.io/alb2/pkg/client/listers/alauda/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ALB2Informer provides access to a shared informer and lister for
// ALB2s.
type ALB2Informer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ALB2Lister
}

type aLB2Informer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewALB2Informer constructs a new informer for ALB2 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewALB2Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredALB2Informer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredALB2Informer constructs a new informer for ALB2 type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredALB2Informer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().ALB2s(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().ALB2s(namespace).Watch(context.TODO(), options)
			},
		},
		&alaudav1.ALB2{},
		resyncPeriod,
		indexers,
	)
}

func (f *aLB2Informer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredALB2Informer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *aLB2Informer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alaudav1.ALB2{}, f.defaultInformer)
}

func (f *aLB2Informer) Lister() v1.ALB2Lister {
	return v1.NewALB2Lister(f.Informer().GetIndexer())
}
