apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alb-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services", "pods","secrets","namespaces","events","serviceaccounts"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "services","events","serviceaccounts","events"]
    verbs: ["create","update","delete","patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create","update","patch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["crd.alauda.io"]
    resources: ["alaudaloadbalancer2","alaudaloadbalancer2/status", "frontends","frontends/status", "rules"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["crd.alauda.io"]
    resources: ["alaudaloadbalancer2","alaudaloadbalancer2/status"]
    verbs: ["update", "patch","create","delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list","update", "watch","delete"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses","gatewayclasses/status", "gateways","gateways/stauts"]
    verbs: ["get", "list", "watch","update", "patch","create","delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch","update", "patch","create","delete"]
  - apiGroups: ["infrastructure.alauda.io"]
    resources: ["features"]
    verbs: ["get", "list", "watch","update", "patch","create","delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles","clusterrolebindings"]
    verbs: ["get", "list", "watch","update", "patch","create","delete"]