apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      workspaces:
      - name: source
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 500Mi
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
  tasks:
    - name: kind-test 
      params:
      - name: chart
        value: $(params.chart)
      retries: 3
      workspaces:
        - name: source
          workspace: source
      taskSpec:
        descriptifn: >
          run alb kind e2e test
        workspaces:
          - name: source
            workspace: source
        steps:
          - image: build-harbor.alauda.cn/ops/golang:1.18-alpine3.16  # keep it as same as alb docker builder.
            name: build
            imagePullPolicy: IfNotPresent
            workingDir: '$(workspaces.source.path)'
            params:
              - name: chart 
                value: "$(params.chart)"
            resources:
              requests:
                cpu: "1"
                memory: "1G"
              limits:
                cpu: "2"
                memory: "2G"              
            script: |
              #!/bin/sh
              sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
              apk update
              apk add bash openssh-client sshpass git gcc
              ls
              env
              pwd
              export ALB_KIND_E2E_CHART=$(params.chart)
              echo "branch  is  $ALB_KIND_E2E_BRANCH. version is $ALB_KIND_E2E_CHART"
              bash ./scripts/kind-e2e.sh
              echo "just ignore error"