apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  runTemplate:
    spec:
      workspaces:
      - name: source
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteMany
            resources:
              requests:
                storage: 500Mi
  workspaces:
    - description: >
        This workspace is shared among all the pipeline tasks to read/write
        common resources
      name: source
  tasks:
    - name: version
      timeout: 5m
      retries: 1
      workspaces:
        - name: source
          workspace: source
      taskRef:
        kind: ClusterTask
        name: alauda-generate-version
      params:
        - name: repo-type
          value: gitlab
        - name: repo-url
          value: $(params.git-url)
        - name: repo-ref
          value: $(params.git-revision)
    - name: build-alb-nginx
      timeout: 100m
      retries: 3
      taskRef:
        kind: ClusterTask
        name: alauda-build-image
      workspaces:
        - name: source
          workspace: source
      params:
        - name: container-image
          value: build-harbor.alauda.cn/3rdparty/alb-nginx
        - name: container-image-tag
          value: "v1.25.3.$(tasks.version.results.timestamp)"
        - name: dockerfile
          value: ./template/Dockerfile.openresty
        - name: platform
          value:
            - linux/amd64
            - linux/arm64
        - name: verbose
          value: "true"
        - name: labels
          value:
          - commit=$(build.git.lastCommit.id)
          - branch=$(build.git.branch.name)