---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustercredentials.platform.tkestack.io
spec:
  group: platform.tkestack.io
  names:
    kind: ClusterCredential
    listKind: ClusterCredentialList
    plural: clustercredentials
    shortNames:
      - cc
    singular: clustercredential
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                token:
                  type: string
      served: true
      storage: true