---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.platform.tkestack.io
spec:
  conversion:
    strategy: None
  group: platform.tkestack.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Cluster
  versions:
    - name: v1
      additionalPrinterColumns:
      - name: state
        type: string
        jsonPath: .spec.state
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                state:
                  type: string
                clusterCredentialRef:
                  type: object
                  properties:
                    name:
                      type: string
            status:
              type: object
              properties:
                addresses:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      host:
                        type: string
                      port:
                        type: integer
      served: true
      storage: true