FROM openresty/openresty:alpine-fat
RUN luarocks install busted && \
    luarocks install luacheck && \
    luarocks install luacov && \
    luarocks install lua-resty-http

ENV LUA_PATH $LUA_PATH;/alb-nginx/lua/?.lua
WORKDIR /alb-nginx
