/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ALB2ListerExpansion allows custom methods to be added to
// ALB2Lister.
type ALB2ListerExpansion interface{}

// ALB2NamespaceListerExpansion allows custom methods to be added to
// ALB2NamespaceLister.
type ALB2NamespaceListerExpansion interface{}

// FrontendListerExpansion allows custom methods to be added to
// FrontendLister.
type FrontendListerExpansion interface{}

// FrontendNamespaceListerExpansion allows custom methods to be added to
// FrontendNamespaceLister.
type FrontendNamespaceListerExpansion interface{}

// RuleListerExpansion allows custom methods to be added to
// RuleLister.
type RuleListerExpansion interface{}

// RuleNamespaceListerExpansion allows custom methods to be added to
// RuleNamespaceLister.
type RuleNamespaceListerExpansion interface{}
