--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cong.
--- DateTime: 2021/11/16 下午6:27

local common = require "utils.common"
local ngx_log = ngx.log
local ngx_err = ngx.ERR

local function trace(log)
    local enable = false
    if enable then
        ngx_log(ngx_err, "trace "..log())
    end
end

local _M = {}

function _M.header_filter()
    local ngx_header = ngx.header
    local matched_policy = ngx.ctx.matched_policy
    trace(function()
        return "rewrite_response: policy is " .. common.dump(matched_policy)
    end)
    -- fast return
    if not common.has_key(matched_policy, { "config", "rewrite_response", "headers" })
    then
        trace(function()
            return "rewrite_response: could not find config,just ignore"
        end)
        return
    end
    local headers = matched_policy["config"]["rewrite_response"]["headers"]
    for k, v in pairs(headers) do
        ngx_header[k] = v
    end
end

return _M