--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cong.
--- DateTime: 2021/11/16 下午6:27
local common = require "utils.common"
local ngx_log = ngx.log
local ngx_err = ngx.ERR

local function trace(log)
    local enable = false
    if enable then
        ngx_log(ngx_err, "trace " .. log())
    end
end

local _M = {}

function _M.header_filter()
    local ngx_header = ngx.header
    local matched_policy = ngx.ctx.matched_policy
    trace(function()
        return "rewrite_response: policy is " .. common.dump(matched_policy)
    end)
    -- fast return
    if not common.has_key(matched_policy, {"config", "rewrite_response"}) then
        trace(function()
            return "rewrite_response: could not find config,just ignore"
        end)
        return
    end
    -- headers_set(headers) set header and values anywhere
    -- headers_remove remove header
    -- headers_update set header only when it exist
    -- headers_default set header only when it not exist

    local headers_set = matched_policy["config"]["rewrite_response"]["headers"]
    if headers_set then
        for k, v in pairs(headers_set) do
            ngx_header[k] = v
        end
    end

    local headers_remove = matched_policy["config"]["rewrite_response"]["headers_remove"]
    if headers_remove then
        for _, h in pairs(headers_remove) do
            if ngx.header[h] then
                ngx_header[h] = nil
            end
        end
    end

    local headers_default = matched_policy["config"]["rewrite_response"]["headers_default"]
    if headers_default then
        for k, v in pairs(headers_default) do
            if ngx.header[k] == nil then
                ngx_header[k] = v
            end
        end
    end

    local headers_update = matched_policy["config"]["rewrite_response"]["headers_update"]
    if headers_update then
        for k, v in pairs(headers_update) do
            if ngx.header[k] then
                ngx_header[k] = v
            end
        end
    end

    local headers_add = matched_policy["config"]["rewrite_response"]["headers_add"]
    if headers_add then
        for k, vlist in pairs(headers_add) do
            if ngx.header[k] == nil then
                ngx_header[k] = ""
            else
                for _, v in pairs(vlist) do
                    ngx_header[k] = ngx_header[k] .. "," .. v
                end
            end
        end
    end

end

return _M
