name: alauda-alb2
version: v3.19.0-beta.18.ge3f785dd
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: e3f785dd050ce59a75a8da7f5b72c1c5f4400a32
