name: alauda-alb2
version: v3.19.0-beta.19.g9ec78766
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: 9ec78766dd8050e98bb4f9cc1fdd3960dfe42cf6
