name: alauda-alb2
version: v3.16.0-beta.16.g56454218
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: 56454218142fa9aaecd5582d8bfaaa9903221795
