name: alauda-alb2
version: v3.18.0-beta.3.gfa41e863
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: fa41e863b00eb27043c8412d3b7b2899b16bd651
