name: alauda-alb2
version: v3.19.0-beta.13.g7995b13b
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: 7995b13bbc98ab2dfcf03ffef9b9bf905e4f54f7
