name: alauda-alb2
version: v3.18.0-beta.6.g268f238b
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: 268f238befd0247be2ef284ca38efa5879366ea2
