name: alauda-alb2
version: v3.19.0-beta.3.gceb48598
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: ceb48598916da698dea53d6a70dbae2f0cf4c422
