name: alauda-alb2
version: v3.19.0-beta.12.g9d9db164
description: alauda loadbalancer version 2
apiVersion: v2
annotations:
  release: alpha
  branch: master
  commit: 9d9db164c61d27ae1cf8fc70da978d98325e8b7d
