apiVersion: cluster.alauda.io/v1alpha1
kind: ModulePlugin
metadata:
  annotations:
    cpaas.io/module-name: "alb"
    cpaas.io/display-name: '{"en": "Alauda Container Platform (ACP) Ingress Gateway", "zh": "Alauda Container Platform (ACP) Ingress Gateway"}'
    cpaas.io/built-in-plugin: "true"
  labels:
    cpaas.io/module-type: plugin
    cpaas.io/module-name: alb
    cpaas.io/auto-install: "true"
  name: alb
spec:
  name: alb
  logo: "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTIyLjIyMiAxMC42YS41OS41OSAwIDAgMSAuNTkyLjU1NXY5LjY3NmMwIC42MzMtLjUxIDEuMTUtMS4xNDcgMS4xNjhMMjEuNjMgMjJIMi4wNzRBMS4xNzggMS4xNzggMCAwIDEgLjg5IDIwLjg2N3YtLjAzNmwtLjAwMS0yLjYwN0ExLjQ2MSAxLjQ2MSAwIDAgMSAwIDE2Ljg4NGMwLS44MDcuNjYzLTEuNDYgMS40ODEtMS40Ni44MTkgMCAxLjQ4Mi42NTMgMS40ODIgMS40NiAwIC42LS4zNjUgMS4xMTQtLjg4OCAxLjM0djIuNjA3SDIxLjYzdi05LjY0NmMwLS4zMjMuMjY1LS41ODUuNTkyLS41ODV6TTE5IDZ2My4xNmgtMy4xNXYtLjYzbC0uOTggMS4yNC0uNDUtLjYzNS00LjQzNyAyLjg0aDMuNzY1VjExLjNsMi4xMDIuNzg3di0xLjE2NUgxOXYzLjE2aC0zLjE1VjEyLjkybC0yLjEwMi43ODd2LS42NzRIOS45ODNsNC40OCAyLjg0LjQwOC0uNjYyLjk3OSAxLjI2di0uNjNIMTlWMTloLTMuMTV2LTEuMjY1bC0yLjE3OC0uNTIzLjI5NS0uNjM2LTUuNDY1LTMuNTU3djIuMTFINXYtNS4yN2gzLjUwMnYyLjEwOWw1LjUxLTMuNTUtLjM0LS42MzYgMi4xNzgtLjUyM1Y2SDE5em0yLjYzLTNjLjY0MiAwIDEuMTY1LjUwNCAxLjE4NCAxLjEzM3YyLjExMkExLjQ2NyAxLjQ2NyAwIDAgMSAyNCA3LjY3N2MwIC44MDctLjY2MyAxLjQ2MS0xLjQ4MSAxLjQ2MWExLjQ3MiAxLjQ3MiAwIDAgMS0xLjQ4Mi0xLjQ2MWMwLS40NzguMjMyLS45MDIuNTkyLTEuMTY5VjQuMTdIMi4wNzV2OS41YS41ODkuNTg5IDAgMCAxLS41OTMuNTg1LjU5LjU5IDAgMCAxLS41OTEtLjU1NmwtLjAwMS0uMDI5di05LjVjMC0uNjMzLjUxLTEuMTUgMS4xNDgtMS4xNjhMMjEuNjMgM3oiIGZpbGw9IiMwMDdBRjUiIGZpbGwtcnVsZT0ibm9uemVybyIvPjwvc3ZnPg=="
  description:
    en: "Load Balancer Operator"
    zh: "负载均衡器 Operator"
  deleteable: false
  labelCluster: "false"
  appReleases:
  - name: alauda-alb2
    chartVersions:
    - name: acp/chart-alauda-alb2
      releaseName: alauda-alb2
      version: v3.19.0-beta.20.g84a472c2
  mainChart: acp/chart-alauda-alb2
  upgradeRiskLevel: High
  upgradeRiskDescription: "升级期间可能会短暂影响用户已部署的应用的访问."
  upgradeRiskDescriptionEn: "During the upgrade, there may be a temporary impact on the access to applications already deployed by users."

