## global
operator:
  albImagePullPolicy: Always
defaultAlb: true # 部署默认的alb
operatorReplicas: 1
operatorDeployMode: "deployment"
displayName: ""
address: 127.0.0.1 # address of the default alb
projects: []
global:
  platformscenario: base
  labelBaseDomain: cpaas.io
  namespace: cpaas-system
  registry:
    address: registry.alauda.cn:60080
  images:
    alb2:
      code: gitlab-ce.alauda.cn/container-platform/alb2
      support_arm: true
      repository: acp/alb2
      tag: v3.19.0-beta.13.g7995b13b
    nginx:
      code: gitlab-ce.alauda.cn/container-platform/alb2
      support_arm: true
      repository: acp/alb-nginx
      tag: "v3.19.0-beta.13.g7995b13b"
resources:
  alb:
    limits:
      cpu: "200m"
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 128Mi
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 50m
    memory: 128Mi
