## global
address: 127.0.0.1 # address of the default alb
global:
  platformscenario: base
  labelBaseDomain: cpaas.io
  namespace: cpaas-system
  registry:
    address: harbor.alauda.cn
  images:
    alb2:
      code: gitlab-ce.alauda.cn/container-platform/alb2
      support_arm: true
      repository: acp/alb2
      tag: v3.12-6-g85eebe95
    nginx:
      code: gitlab-ce.alauda.cn/container-platform/alb2
      support_arm: true
      repository: acp/alb-nginx
      tag: "v3.12-6-g85eebe95"
resources:
  alb:
    limits:
      cpu: "200m"
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 128Mi
