apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alaudaloadbalancer2.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: alaudaloadbalancer2
    singular: alaudaloadbalancer2
    kind: ALB2
    shortNames:
    - alb2
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: spec contains specification parameters for a alb2 resource
          type: object
          properties:
            address:
              description: address is used to shown access address if no domain
              type: string
            bind_address:
              description: deprecated field
              type: string
            type:
              description: deprecated field
              type: string
            domains:
              description: deprecated field
              anyOf:
              - type: array
                items:
                  type: string
              - type: null