# https://gitlab-ce.alauda.cn/ait/chart-alauda-cluster-base/blob/master/chart/crds/infrastructure.alauda.io_features.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: features.infrastructure.alauda.io
spec:
  conversion:
    strategy: None
  group: infrastructure.alauda.io
  names:
    kind: Feature
    listKind: FeatureList
    plural: features
    shortNames:
      - ft
    singular: feature
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                accessInfo:
                  description: accessInfo defines the server info,if
                    the addon support some interface to access. eg
                    promtheus, grafana
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                deployInfo:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                instanceType:
                  description: 'instanceType defines the tool to support
                                    the type. eg: prometheus, fluentd'
                  type: string
                resourceInfo:
                  description: resourceInfo defines all the resource
                    the addons contains
                  items:
                    properties:
                      kind:
                        type: string
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                  type: array
                type:
                  description: 'type defines the type of the addon.
                                    eg: metric, log, application etc...'
                  type: string
                version:
                  description: version defines the version of the addon.
                    it is used to compare with the version of the
                    instance to descide upgrade or not
                  type: string
              required:
                - version
                - type
              type: object
            status:
              properties:
                status:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
          type: object
      served: true
      storage: true
