//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package types

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchSpanProcessor) DeepCopyInto(out *BatchSpanProcessor) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchSpanProcessor.
func (in *BatchSpanProcessor) DeepCopy() *BatchSpanProcessor {
	if in == nil {
		return nil
	}
	out := new(BatchSpanProcessor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Collector) DeepCopyInto(out *Collector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Collector.
func (in *Collector) DeepCopy() *Collector {
	if in == nil {
		return nil
	}
	out := new(Collector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Exporter) DeepCopyInto(out *Exporter) {
	*out = *in
	if in.Collector != nil {
		in, out := &in.Collector, &out.Collector
		*out = new(Collector)
		**out = **in
	}
	if in.BatchSpanProcessor != nil {
		in, out := &in.BatchSpanProcessor, &out.BatchSpanProcessor
		*out = new(BatchSpanProcessor)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Exporter.
func (in *Exporter) DeepCopy() *Exporter {
	if in == nil {
		return nil
	}
	out := new(Exporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flags) DeepCopyInto(out *Flags) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flags.
func (in *Flags) DeepCopy() *Flags {
	if in == nil {
		return nil
	}
	out := new(Flags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelConf) DeepCopyInto(out *OtelConf) {
	*out = *in
	if in.Exporter != nil {
		in, out := &in.Exporter, &out.Exporter
		*out = new(Exporter)
		(*in).DeepCopyInto(*out)
	}
	if in.Sampler != nil {
		in, out := &in.Sampler, &out.Sampler
		*out = new(Sampler)
		(*in).DeepCopyInto(*out)
	}
	if in.Flags != nil {
		in, out := &in.Flags, &out.Flags
		*out = new(Flags)
		**out = **in
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelConf.
func (in *OtelConf) DeepCopy() *OtelConf {
	if in == nil {
		return nil
	}
	out := new(OtelConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtelCrConf) DeepCopyInto(out *OtelCrConf) {
	*out = *in
	in.OtelConf.DeepCopyInto(&out.OtelConf)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtelCrConf.
func (in *OtelCrConf) DeepCopy() *OtelCrConf {
	if in == nil {
		return nil
	}
	out := new(OtelCrConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sampler) DeepCopyInto(out *Sampler) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = new(SamplerOptions)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sampler.
func (in *Sampler) DeepCopy() *Sampler {
	if in == nil {
		return nil
	}
	out := new(Sampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SamplerOptions) DeepCopyInto(out *SamplerOptions) {
	*out = *in
	if in.ParentName != nil {
		in, out := &in.ParentName, &out.ParentName
		*out = new(string)
		**out = **in
	}
	if in.Fraction != nil {
		in, out := &in.Fraction, &out.Fraction
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SamplerOptions.
func (in *SamplerOptions) DeepCopy() *SamplerOptions {
	if in == nil {
		return nil
	}
	out := new(SamplerOptions)
	in.DeepCopyInto(out)
	return out
}
