apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rules.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - rl
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: spec contains specification parameters for a rule resource
          type: object
          properties:
            description:
              description: the description of this rule
              type: string
            domain:
              description: domain of this rule
              type: string
            dsl:
              description: internal dsl
              type: string
            priority:
              description: weight of this rule
              type: integer
            type:
              description: deprecated field
              type: string
            url:
              description: url rewrite src
              type: string
            certificate_name:
              description: certificate_name is the default certificate
              type: string
            rewrite_target:
              description: url rewrite dest
              type: string
            enableCORS:
              description: if need enable cors headers
              type: boolean
            backendProtocol:
              description: http/https/grpc/grpcs
              type: string
            serviceGroup:
              description: serviceGroup is a group of k8s services
              type: object
              properties:
                session_affinity_policy:
                  description: session_affinity_policy is the hash algo
                  type: string
                session_affinity_attribute:
                  description: session_affinity_attribute is needed if using cookie hash
                  type: string
                services:
                  description: services is a list of k8s services
                  type: array
                  items:
                    description: items is a list of service
                    type: object
                    properties:
                      name:
                        description: name is the k8s service name
                        type: string
                      namespace:
                        description: namespace is the k8s service namespace
                        type: string
                      port:
                        description: port is the k8s service port
                        type: integer
                      weight:
                        description: weight is the weight of this service
                        type: integer
            source:
              type: object
              description: source indicate who created this resource, ingress or UI
              properties:
                name:
                  description: source name
                  type: string
                namespace:
                  description: source namespace
                  type: string
                type:
                  description: source type
                  type: string
