---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: alb2
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - update
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - crd.alauda.io
    resources:
      - alaudaloadbalancer2
      - frontends
      - rules
    verbs:
      - get
      - create
      - update
      - list
      - delete
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - create
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: alb2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb2
subjects:
- kind: ServiceAccount
  name: alb2
  namespace: kube-system
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: alb2
  namespace: kube-system
