apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: alaudaloadbalancer2.crd.alauda.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: crd.alauda.io
  version: v1
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: alaudaloadbalancer2
    # singular name to be used as an alias on the CLI and for display
    singular: alaudaloadbalancer2
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ALB2
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - alb2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: frontends.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: frontends
    singular: frontend
    kind: Frontend
    shortNames:
    - ft
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rules.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - rl