apiVersion: crd.alauda.io/v1
kind: ALB2
metadata:
  name: test1
  namespace: default
spec:
  address: "1.2.3.4"
  type: "haproxy"

---

apiVersion: crd.alauda.io/v1
kind: Frontend
metadata:
  name: test1-80
  namespace: default
  labels:
    alb2.alauda.io/name: test1
spec:
  port: 80
  protocol: http
  serviceGroup:
    session_affinity_policy: ""
    session_affinity_attribute: ""
    services:
      - name: test
        namespace: default
        port: 80
        weight: 100


---

apiVersion: crd.alauda.io/v1
kind: Rule
metadata:
  name: test1-80
  namespace: default
  labels:
    alb2.alauda.io/name: test1
    alb2.alauda.io/frontend: test1-80
spec:
  priority: 10000
  domain: "test1.example.com"
  url: "/"
  dsl: ""
  description: "test1-rule"
  serviceGroup:
    session_affinity_policy: ""
    session_affinity_attribute: ""
    services:
      - name: test
        namespace: default
        port: 80
        weight: 100
