apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: alaudaloadbalancer2.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: alaudaloadbalancer2
    singular: alaudaloadbalancer2
    kind: ALB2
    shortNames:
    - alb2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: frontends.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: frontends
    singular: frontend
    kind: Frontend
    shortNames:
    - ft

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rules.crd.alauda.io
spec:
  group: crd.alauda.io
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - rl
