name: build-alb-images-and-chart
on:
  workflow_dispatch:
    inputs:
      do_release:
        type: boolean
        description: do release 
        required: true
  pull_request:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - '.github/VERSION'
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  GO_VERSION: ''
  GOSEC_VERSION: '2.18.2'
  HELM_VERSION: v3.13.3
  SUBMARINER_VERSION: '0.16.2'
jobs:
  build-alb:
    name: Build alb
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: version # it will set the CURRENT_VERSION env
        uses: HardNorth/github-version-generate@v1.3.0
        with:
          version-source: file
          version-file: ./deploy/chart/alb/Chart.yaml
          version-file-extraction-pattern: 'version: v([0-9]*\.[0-9]*\.[0-9]*)'
      - uses: docker/setup-buildx-action@v3
      - name: test alb go 
        if: ${{ matrix.platform ==  'linux/amd64' }}
        env:
            MATRIX_PLATFORM: "${{ matrix.platform }}"
        run: |
          set -x
          echo "FROM --platform=\${{ matrix.platform }} | $MATRIX_PLATFORM "
          ./scripts/run-like-github-actions.sh test-alb-go
      - name: build
        env:
            RELEASE_ME: "${{ github.event.inputs.do_release == 'true' }}"
            MATRIX_PLATFORM: "${{matrix.platform }}"
        run: |
          set -x
          ./scripts/run-like-github-actions.sh build-alb
      - name: Upload alb images to artifact
        uses: actions/upload-artifact@v3
        with:
          name: alb
          path: alb.tar
      - name: test alb nginx
        env:
            MATRIX_PLATFORM: "${{matrix.platform }}"
        run: |
          set -x
          ./scripts/run-like-github-actions.sh test-alb-nginx
  release-alb:
    name: Release alb
    runs-on: ubuntu-22.04
    needs: [build-alb]
    steps:
      - name: cr
        uses: helm/chart-releaser-action@v1.6.0
        with:
          install_only: true
      - uses: azure/setup-helm@v3
        with:
          version: '${{ env.HELM_VERSION }}'
      - name: Upload chart's to artifact
        uses: actions/upload-artifact@v3
        with:
          name: alb-chart
          path: alauda-alb2.tgz
      - name: release
        if: ${{ inputs.do_release }}
        env:
          RELEASE_ME: "${{ github.event.inputs.do_release == 'true' }}"
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          ./scripts/run-like-github-actions.sh release-alb